# Generated by Django 2.2.6 on 2019-11-30 02:51

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='case',
            name='preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='case_previews'),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='doc_previews'),
        ),
        migrations.AlterField(
            model_name='docketentry',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docket_entries', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docket_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.DocketEntry'),
        ),
    ]
