# Generated by Django 2.2.6 on 2019-12-01 04:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cases', '0005_auto_20191201_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='organizations',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='org_cases', through='cases.OrgTagged', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='case',
            name='people',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='person_cases', through='cases.PersonTagged', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
