# Generated by Django 2.2.6 on 2019-12-01 11:38

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cases', '0006_auto_20191201_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CreditorTagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_creditortagged_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_creditortagged_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='case',
            name='creditors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='creditor_cases', through='cases.CreditorTagged', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
