# Generated by Django 2.2.6 on 2019-12-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20191201_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docketentry',
            options={'ordering': ['date_filed', 'date_created']},
        ),
    ]
